trigger:
  batch: true
  branches:
    include:
      - master
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: BuildAndPublish
        steps:
          - script: |
              sbt universal:packageBin
            displayName: 'Build deployment zip'

          - task: CopyFiles@2
            displayName: 'Copy deployment zip to ArtifactStagingDirectory'
            inputs:
              SourceFolder: 'scala-file-event-processor-function/target/universal'
              Contents: '*.zip'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              FlattenFolders: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish deployment zip'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'FunctionApp deployment zip'
              publishLocation: 'Container'

          - script: |
              sbt publish
            condition: and(succeeded(), eq(variables.publishToMaven, true))
            displayName: 'Publish to Maven'
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)